#!/bin/bash
shopt -s globstar
DOTHOME="$(readlink -f `dirname $0`)"
for FILE in profile bashrc gitconfig vimrc tmux.conf redshift.conf \
	Xresources bash_aliases toprc bin/* config/**/* local/**/*.vim
do
	if ! test -f ${DOTHOME}/${FILE}; then
		echo ${FILE} is removed from git repo - update $0
		continue
	fi
	case $FILE in
	bin/*)
		TARGET=${HOME}/${FILE}
		;;
	*)
		TARGET=${HOME}/.${FILE}
		;;
	esac
	if test -L ${TARGET}.bak; then
		rm -v ${TARGET}.bak
	fi
	if test \( -f ${TARGET} \) -a \( ! -L ${TARGET} \); then
		mv -v ${TARGET} ${TARGET}.bak
	fi
	if ! test -s ${TARGET}; then
		mkdir -p $(dirname $TARGET)
		ln -sfv ${DOTHOME}/${FILE} $TARGET
	fi
done
